# For your notes during the hands-on:
# Download the file and open it with Visual Studio Code to get a nice formatting and highlighting.
    

# BTP Login Credentials: 
    User                    = 
                            # Note: You should never note passwords - only for demo purposes
    Password                = 
    IdentityProvider        = 


# Customer Subaccount:
    LaunchpadSiteURL        = 
    CustomerSubdomain       =


    # Service key of the service broker instance *psm-sb-sub1-full*:
        ServiceBrokerEndpoint        =
        ServiceBrokerClientID        =
        ServiceBrokerClientSecret    =  
                                        # Should end with `/oauth/token`
        ServiceBrokerTokenServiceURL = 

# Provider Subaccount:
    # Provider MTX 
    # Note: You should never note client credentials of a productive tenant - only for demo purposes
        ProviderMTXURL         = URL
        MTXClientID            =  
        MTXClientSecret        =       


# Statements:
    # Log in to the MTX module:
    # Replace <CustomerSubdomain> with the CustomerSubdomain
    cds login
